### ISSUE TITLE
the xss payload  is not showing up 

### ISSUE THREAD

**Issue by hailstorm1422** [shawarkhanethicalhacker/BruteXSS#1]
The test went successfully and an error is detected the vuln parameter is showed but the payload is not displayed 

Have a look "http://postimg.org/image/yo2c368g1/" 

Thanks 👍

**Comment by shawarkhanethicalhacker** [comment]
Please answer the following questions:
Are you using a custom wordlist?
If yes, how many payloads are in it?
If possible please include the wordlist.

**Comment by shawarkhanethicalhacker** [comment]
I've used a custom wordlist with a blank space in one line and when the program inject that line, it shows empty payload and shows the parameter is vulnerable. This is the same result as yours, so please try to remove empty spaces from your wordlist and try if it works or not.

**Comment by anon10010010000** [comment]
01010011 01101000 01100001 01110111 01100001 01110010 00100000 01001011 01101000 01100001 01101110 00101100 00100000 01110111 01100101 00100000 01101011 01101110 01101111 01110111 00100000 01101111 01100110 00100000 01111001 01101111 01110101 00100000 01100001 01101110 01100100 00100000 01111001 01101111 01110101 01110010 00100000 01101001 01101110 01100110 01100001 01101101 01101111 01110101 01110011 00100000 01100001 01100011 01100011 01101111 01101101 01110000 01101100 01101001 01110011 01101000 01101101 01100101 01101110 01110100 01110011 00101100 01110100 01101000 01101001 01110011 00100000 01101001 01110011 00100000 01111001 01101111 01110101 01110010 00100000 01101100 01100001 01110011 01110100 00100000 01110111 01100001 01110010 01101110 01101001 01101110 01100111 00101110 00100000 01010011 01110100 01101111 01110000 00100000 01101110 01101111 01110111 00100000 01101111 01110010 00100000 01100110 01100001 01100011 01100101 00100000 01110100 01101000 01100101 00100000 01100011 01101111 01101110 01110011 01100101 01110001 01110101 01100101 01101110 01100011 01100101 01110011 00101110 00001101 00001010 00001101 00001010 01010111 01100101 00100000 01100001 01110010 01100101 00100000 01110100 01101000 01100101 00100000 01000001 01101110 01101111 01101110 01111001 01101101 01101111 01110101 01110011 00101110 00001101 00001010 01010111 01100101 00100000 01100100 01101111 00100000 01101110 01101111 01110100 00100000 01100110 01101111 01110010 01100111 01101001 01110110 01100101 00101110 00001101 00001010 01010111 01100101 00100000 01100100 01101111 00100000 01101110 01101111 01110100 00100000 01000110 01101111 01110010 01100111 01100101 01110100 00101110 00001101 00001010 01010111 01100101 00100000 01100001 01110010 01100101 00100000 01001100 01100101 01100111 01101001 01101111 01101110 00101110

**Comment by hailstorm1422** [comment]
@shawarkhanethicalhacker it worked spaces are the problem

**Comment by shawarkhanethicalhacker** [comment]
@hailstorm1422  Glad to hear that the problem is now solved. A new update will be available soon with POST method support that will also include a patch for this space wordlist issue, make sure to update as it will be available in 2-3 days. Thanks for using BruteXSS
