### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xorond** [shawarkhanethicalhacker/BruteXSS#2]
Hello,

I would like to add your tool into ArchStrike but it looks like you don't have a license file.

Do you think you can add one?

Thanks

**Comment by shawarkhanethicalhacker** [comment]
I've added the license.


Regards,

*Shawar Khan*
Web Application Security Researcher

**Comment by xorond** [comment]
Thank you,

I will be adding the tool as soon as possible.

xorond - ArchStrike Developer

**Comment by xorond** [comment]
Just added brutexss to ArchStrike!

https://archstrike.org/packages/brutexss-git

**Comment by shawarkhanethicalhacker** [comment]
Great! can you replaced the name "brutexss-git" to "BruteXSS"


Regards,

*Shawar Khan*
Web Application Security Researcher

**Comment by xorond** [comment]
Hello,

If you have a look at our other packages, you'll notice that we name packages which don't have a release number with a -git in the end. So I'm afraid it won't happen until there is a stable release of this package. We also don't use capital letter in our package names. (So if there's a new release it will be renamed to 'brutexss')

Cheers
