### ISSUE TITLE
GNU GPL Concerns

### ISSUE THREAD

**Issue by kevcody** [shawarkhanethicalhacker/BruteXSS#4]
Hi Shawar,

Great work on BruteXSS. I simply have a general concern regarding your Readme statement vs. utilization of the GNU GPL.

In your readme you have a line: "WARNING: Copying or modification of this tool without permission is not allowed!"

This somewhat flies in conflict with the GNU GPL License. I am in no way trying to rip your software off; however, simply wanted to bring this to your attention, as it may cause you some headaches in the future.

Cheers,
Kevin Cody

**Comment by saxbophone** [comment]
+1 On this. The declaration at the top of the project's README file contradicts the license terms of the GPL, it would be great to have the exact license terms clarified.

Of course it goes without saying that you're free to assert your copyright in any way you wish, but using conflicting terms will likely cause problems for you and any potential contributors or users of the software.

Btw, the library looks great, I wish you well on any future development!

**Comment by shawarkhanethicalhacker** [comment]
Thanks for informing, i've removed the line from the ReadMe. Hope its okay now.

**Comment by saxbophone** [comment]
Great stuff!
